image = "../../assets/services/cisterna_agua.jpg"
title = "Cisternas para agua potable"
description = "Construimos cisternas de concreto reforzado monolítico e impermeabilizado para almacenar grandes cantidades de agua potable, ajustando las dimensiones a las capacidades que necesites almacenar."
