image = "../../assets/services/movimientos_en_tierra.jpg"
title = "Movimientos de tierras, bodegas, naves industriales"
description = "Ofrecemos la construcción de movimientos de tierra, bodegas, naves industriales y locales comerciales a un costo accesible y con tiempos de ejecución óptimos."
