image = "../../assets/services/muro_blokon.jpg"
title = "Muros Block On"
description = "Construimos muros perimetrales con materiales prefabricados que tienen la apariencia de un muro de bloques. Este servicio ofrece bajos costos, buena estética, seguridad, durabilidad y una instalación rápida."
