image = "../../assets/services/muro_loseta.jpg"
title = "Muros de losetas lisas"
description = "Construimos muros perimetrales con materiales prefabricados que tienen la apariencia de un muro de bloques. Este servicio ofrece bajos costos, seguridad, durabilidad y una instalación rápida."
