image = "../../assets/services/sistema_bombeo.jpg"
title = "Sistema de bombeo de agua a presión continua"
description = "Suministramos e instalamos un sistema de bombeo automatizado para garantizar un suministro de agua continuo e ininterrumpido en el hogar, ideal para una familia de 5 personas."
