image = "../../assets/services/tanque_septico.jpg"
title = "Tanques sépticos y pozos de absorción"
description = "Ofrecemos soluciones para el tratamiento de aguas residuales con sistemas de tanques sépticos y pozos de absorción, brindando una alternativa económica y duradera."
