image = "../../assets/services/torre_metalica.jpg"
title = "Torre metálica para soporte de tanques"
description = "Garantizamos el suministro de agua potable automatizado e ininterrumpido al hogar por medio de la fuerza de gravedad."
